
package com.sps.ws.wsdl.mtom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MTOM", targetNamespace = "http://ws.sps.com/wsdl/Mtom/", wsdlLocation = "/resources/Mtom.wsdl")
public class MTOM
    extends Service
{

    private final static URL MTOM_WSDL_LOCATION;
    private final static WebServiceException MTOM_EXCEPTION;
    private final static QName MTOM_QNAME = new QName("http://ws.sps.com/wsdl/Mtom/", "MTOM");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("/resources/Mtom.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTOM_WSDL_LOCATION = url;
        MTOM_EXCEPTION = e;
    }

    public MTOM() {
        super(__getWsdlLocation(), MTOM_QNAME);
    }

    public MTOM(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTOM_QNAME, features);
    }

    public MTOM(URL wsdlLocation) {
        super(wsdlLocation, MTOM_QNAME);
    }

    public MTOM(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTOM_QNAME, features);
    }

    public MTOM(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTOM(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MtomPort
     */
    @WebEndpoint(name = "MtomSOAP")
    public MtomPort getMtomSOAP() {
        return super.getPort(new QName("http://ws.sps.com/wsdl/Mtom/", "MtomSOAP"), MtomPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MtomPort
     */
    @WebEndpoint(name = "MtomSOAP")
    public MtomPort getMtomSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sps.com/wsdl/Mtom/", "MtomSOAP"), MtomPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTOM_EXCEPTION!= null) {
            throw MTOM_EXCEPTION;
        }
        return MTOM_WSDL_LOCATION;
    }

}
